//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvilCorp.Commun.EvilCorpService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Staff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        private bool FreeNowField;
        
        private EvilCorp.Commun.EvilCorpService.StaffCategory CategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool FreeNow {
            get {
                return this.FreeNowField;
            }
            set {
                if ((this.FreeNowField.Equals(value) != true)) {
                    this.FreeNowField = value;
                    this.RaisePropertyChanged("FreeNow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public EvilCorp.Commun.EvilCorpService.StaffCategory Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StaffCategory", Namespace="http://tempuri.org/")]
    public enum StaffCategory : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Раб = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Наемник = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Убийца = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Оружейник = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Телохранитель = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Адвокат = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Вор = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EvilCorpService.EvilCorpServiceSoap")]
    public interface EvilCorpServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем LoadStaffResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadStaff", ReplyAction="*")]
        EvilCorp.Commun.EvilCorpService.LoadStaffResponse LoadStaff(EvilCorp.Commun.EvilCorpService.LoadStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<EvilCorp.Commun.EvilCorpService.LoadStaffResponse> LoadStaffAsync(EvilCorp.Commun.EvilCorpService.LoadStaffRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем staff из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStaff", ReplyAction="*")]
        EvilCorp.Commun.EvilCorpService.AddStaffResponse AddStaff(EvilCorp.Commun.EvilCorpService.AddStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<EvilCorp.Commun.EvilCorpService.AddStaffResponse> AddStaffAsync(EvilCorp.Commun.EvilCorpService.AddStaffRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем staff из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStaff", ReplyAction="*")]
        EvilCorp.Commun.EvilCorpService.UpdateStaffResponse UpdateStaff(EvilCorp.Commun.EvilCorpService.UpdateStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<EvilCorp.Commun.EvilCorpService.UpdateStaffResponse> UpdateStaffAsync(EvilCorp.Commun.EvilCorpService.UpdateStaffRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем staff из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveStaff", ReplyAction="*")]
        EvilCorp.Commun.EvilCorpService.RemoveStaffResponse RemoveStaff(EvilCorp.Commun.EvilCorpService.RemoveStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<EvilCorp.Commun.EvilCorpService.RemoveStaffResponse> RemoveStaffAsync(EvilCorp.Commun.EvilCorpService.RemoveStaffRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadStaff", Namespace="http://tempuri.org/", Order=0)]
        public EvilCorp.Commun.EvilCorpService.LoadStaffRequestBody Body;
        
        public LoadStaffRequest() {
        }
        
        public LoadStaffRequest(EvilCorp.Commun.EvilCorpService.LoadStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadStaffRequestBody {
        
        public LoadStaffRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvilCorp.Commun.EvilCorpService.LoadStaffResponseBody Body;
        
        public LoadStaffResponse() {
        }
        
        public LoadStaffResponse(EvilCorp.Commun.EvilCorpService.LoadStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvilCorp.Commun.EvilCorpService.Staff[] LoadStaffResult;
        
        public LoadStaffResponseBody() {
        }
        
        public LoadStaffResponseBody(EvilCorp.Commun.EvilCorpService.Staff[] LoadStaffResult) {
            this.LoadStaffResult = LoadStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStaff", Namespace="http://tempuri.org/", Order=0)]
        public EvilCorp.Commun.EvilCorpService.AddStaffRequestBody Body;
        
        public AddStaffRequest() {
        }
        
        public AddStaffRequest(EvilCorp.Commun.EvilCorpService.AddStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvilCorp.Commun.EvilCorpService.Staff staff;
        
        public AddStaffRequestBody() {
        }
        
        public AddStaffRequestBody(EvilCorp.Commun.EvilCorpService.Staff staff) {
            this.staff = staff;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvilCorp.Commun.EvilCorpService.AddStaffResponseBody Body;
        
        public AddStaffResponse() {
        }
        
        public AddStaffResponse(EvilCorp.Commun.EvilCorpService.AddStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddStaffResult;
        
        public AddStaffResponseBody() {
        }
        
        public AddStaffResponseBody(int AddStaffResult) {
            this.AddStaffResult = AddStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStaff", Namespace="http://tempuri.org/", Order=0)]
        public EvilCorp.Commun.EvilCorpService.UpdateStaffRequestBody Body;
        
        public UpdateStaffRequest() {
        }
        
        public UpdateStaffRequest(EvilCorp.Commun.EvilCorpService.UpdateStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvilCorp.Commun.EvilCorpService.Staff staff;
        
        public UpdateStaffRequestBody() {
        }
        
        public UpdateStaffRequestBody(EvilCorp.Commun.EvilCorpService.Staff staff) {
            this.staff = staff;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvilCorp.Commun.EvilCorpService.UpdateStaffResponseBody Body;
        
        public UpdateStaffResponse() {
        }
        
        public UpdateStaffResponse(EvilCorp.Commun.EvilCorpService.UpdateStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateStaffResult;
        
        public UpdateStaffResponseBody() {
        }
        
        public UpdateStaffResponseBody(int UpdateStaffResult) {
            this.UpdateStaffResult = UpdateStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveStaff", Namespace="http://tempuri.org/", Order=0)]
        public EvilCorp.Commun.EvilCorpService.RemoveStaffRequestBody Body;
        
        public RemoveStaffRequest() {
        }
        
        public RemoveStaffRequest(EvilCorp.Commun.EvilCorpService.RemoveStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EvilCorp.Commun.EvilCorpService.Staff staff;
        
        public RemoveStaffRequestBody() {
        }
        
        public RemoveStaffRequestBody(EvilCorp.Commun.EvilCorpService.Staff staff) {
            this.staff = staff;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public EvilCorp.Commun.EvilCorpService.RemoveStaffResponseBody Body;
        
        public RemoveStaffResponse() {
        }
        
        public RemoveStaffResponse(EvilCorp.Commun.EvilCorpService.RemoveStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RemoveStaffResult;
        
        public RemoveStaffResponseBody() {
        }
        
        public RemoveStaffResponseBody(int RemoveStaffResult) {
            this.RemoveStaffResult = RemoveStaffResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EvilCorpServiceSoapChannel : EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EvilCorpServiceSoapClient : System.ServiceModel.ClientBase<EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap>, EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap {
        
        public EvilCorpServiceSoapClient() {
        }
        
        public EvilCorpServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EvilCorpServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvilCorpServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvilCorpServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvilCorp.Commun.EvilCorpService.LoadStaffResponse EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap.LoadStaff(EvilCorp.Commun.EvilCorpService.LoadStaffRequest request) {
            return base.Channel.LoadStaff(request);
        }
        
        public EvilCorp.Commun.EvilCorpService.Staff[] LoadStaff() {
            EvilCorp.Commun.EvilCorpService.LoadStaffRequest inValue = new EvilCorp.Commun.EvilCorpService.LoadStaffRequest();
            inValue.Body = new EvilCorp.Commun.EvilCorpService.LoadStaffRequestBody();
            EvilCorp.Commun.EvilCorpService.LoadStaffResponse retVal = ((EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap)(this)).LoadStaff(inValue);
            return retVal.Body.LoadStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EvilCorp.Commun.EvilCorpService.LoadStaffResponse> EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap.LoadStaffAsync(EvilCorp.Commun.EvilCorpService.LoadStaffRequest request) {
            return base.Channel.LoadStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<EvilCorp.Commun.EvilCorpService.LoadStaffResponse> LoadStaffAsync() {
            EvilCorp.Commun.EvilCorpService.LoadStaffRequest inValue = new EvilCorp.Commun.EvilCorpService.LoadStaffRequest();
            inValue.Body = new EvilCorp.Commun.EvilCorpService.LoadStaffRequestBody();
            return ((EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap)(this)).LoadStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvilCorp.Commun.EvilCorpService.AddStaffResponse EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap.AddStaff(EvilCorp.Commun.EvilCorpService.AddStaffRequest request) {
            return base.Channel.AddStaff(request);
        }
        
        public int AddStaff(EvilCorp.Commun.EvilCorpService.Staff staff) {
            EvilCorp.Commun.EvilCorpService.AddStaffRequest inValue = new EvilCorp.Commun.EvilCorpService.AddStaffRequest();
            inValue.Body = new EvilCorp.Commun.EvilCorpService.AddStaffRequestBody();
            inValue.Body.staff = staff;
            EvilCorp.Commun.EvilCorpService.AddStaffResponse retVal = ((EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap)(this)).AddStaff(inValue);
            return retVal.Body.AddStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EvilCorp.Commun.EvilCorpService.AddStaffResponse> EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap.AddStaffAsync(EvilCorp.Commun.EvilCorpService.AddStaffRequest request) {
            return base.Channel.AddStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<EvilCorp.Commun.EvilCorpService.AddStaffResponse> AddStaffAsync(EvilCorp.Commun.EvilCorpService.Staff staff) {
            EvilCorp.Commun.EvilCorpService.AddStaffRequest inValue = new EvilCorp.Commun.EvilCorpService.AddStaffRequest();
            inValue.Body = new EvilCorp.Commun.EvilCorpService.AddStaffRequestBody();
            inValue.Body.staff = staff;
            return ((EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap)(this)).AddStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvilCorp.Commun.EvilCorpService.UpdateStaffResponse EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap.UpdateStaff(EvilCorp.Commun.EvilCorpService.UpdateStaffRequest request) {
            return base.Channel.UpdateStaff(request);
        }
        
        public int UpdateStaff(EvilCorp.Commun.EvilCorpService.Staff staff) {
            EvilCorp.Commun.EvilCorpService.UpdateStaffRequest inValue = new EvilCorp.Commun.EvilCorpService.UpdateStaffRequest();
            inValue.Body = new EvilCorp.Commun.EvilCorpService.UpdateStaffRequestBody();
            inValue.Body.staff = staff;
            EvilCorp.Commun.EvilCorpService.UpdateStaffResponse retVal = ((EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap)(this)).UpdateStaff(inValue);
            return retVal.Body.UpdateStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EvilCorp.Commun.EvilCorpService.UpdateStaffResponse> EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap.UpdateStaffAsync(EvilCorp.Commun.EvilCorpService.UpdateStaffRequest request) {
            return base.Channel.UpdateStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<EvilCorp.Commun.EvilCorpService.UpdateStaffResponse> UpdateStaffAsync(EvilCorp.Commun.EvilCorpService.Staff staff) {
            EvilCorp.Commun.EvilCorpService.UpdateStaffRequest inValue = new EvilCorp.Commun.EvilCorpService.UpdateStaffRequest();
            inValue.Body = new EvilCorp.Commun.EvilCorpService.UpdateStaffRequestBody();
            inValue.Body.staff = staff;
            return ((EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap)(this)).UpdateStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EvilCorp.Commun.EvilCorpService.RemoveStaffResponse EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap.RemoveStaff(EvilCorp.Commun.EvilCorpService.RemoveStaffRequest request) {
            return base.Channel.RemoveStaff(request);
        }
        
        public int RemoveStaff(EvilCorp.Commun.EvilCorpService.Staff staff) {
            EvilCorp.Commun.EvilCorpService.RemoveStaffRequest inValue = new EvilCorp.Commun.EvilCorpService.RemoveStaffRequest();
            inValue.Body = new EvilCorp.Commun.EvilCorpService.RemoveStaffRequestBody();
            inValue.Body.staff = staff;
            EvilCorp.Commun.EvilCorpService.RemoveStaffResponse retVal = ((EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap)(this)).RemoveStaff(inValue);
            return retVal.Body.RemoveStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EvilCorp.Commun.EvilCorpService.RemoveStaffResponse> EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap.RemoveStaffAsync(EvilCorp.Commun.EvilCorpService.RemoveStaffRequest request) {
            return base.Channel.RemoveStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<EvilCorp.Commun.EvilCorpService.RemoveStaffResponse> RemoveStaffAsync(EvilCorp.Commun.EvilCorpService.Staff staff) {
            EvilCorp.Commun.EvilCorpService.RemoveStaffRequest inValue = new EvilCorp.Commun.EvilCorpService.RemoveStaffRequest();
            inValue.Body = new EvilCorp.Commun.EvilCorpService.RemoveStaffRequestBody();
            inValue.Body.staff = staff;
            return ((EvilCorp.Commun.EvilCorpService.EvilCorpServiceSoap)(this)).RemoveStaffAsync(inValue);
        }
    }
}
